Added Project Files
Divyan-H/Auroville-webpage-clone pull request #1
Opened 2023-07-06 15:25 UTC by Divyan-H

2023-07-10 12:14 UTC, sakthibalan15 approved these changes

2023-07-19 04:49 UTC, sangeethailango commented on index.html
> +<div class="navbar">
Use semantic elements and make your code more readable. for example intead of writing <div> tag for the navbar you can use <nav> tag,  for footer  you can use <footer> tag. you can also seperate the pages, section by section by using <section> tag and then inside it you can use <div>. don't use div tag for everything.

2023-07-19 06:07 UTC, sangeethailango requested changes

2023-07-19 06:07 UTC, sangeethailango commented on index.html
> +<div class="navbar">
This code is not easily readable. Use semantic elements to make your code more readable. For example instead of using `div` for the navbar you can use `nav` tag, for footer you can use `footer` tag.  Also you can seperate the layout, section by section, by using `section` tag.  Don't use `div` for everything. Read about semantic tags

2023-07-19 06:07 UTC, sangeethailango commented on index.html
> +
Indent you code properly

2023-07-19 06:07 UTC, sangeethailango commented on index.html
> +      Vision
vision is not a button right? Then why did you use `button` hear? also change this for the other 3(ACTIVITIES, COMMUNITY,  WHAT YOU CAN DO)topics. Don' use any tag, it should be meaningful. use `button` tag only if it is a button

2023-07-19 06:07 UTC, sangeethailango commented on index.html
> +      <p id="nav_border"></p>
Don't use seperate tag for border.

2023-07-19 06:07 UTC, sangeethailango commented on index.html
> +
Unnecessary space

2023-07-19 06:07 UTC, sangeethailango commented on index.html
> +        <button id="Donation_Guidelines">Donation guidelines</button>
My personal advice would be use, `span` or `p` tag inside button tag.  so that it will be easier for you to style accordingly.

2023-07-19 06:07 UTC, sangeethailango commented on index.html
> +      <h1 class="title">News & Events in Auroville</h1>
Use h1 tag only once in one page. There is a hierarchical level in heading tag. h1 to h2. After you use h1 you should use h2 you cannot skip h2 and jumpt into h3.  Read the below to understand this better
https://www.w3schools.com/tags/tag_hn.asp

2023-07-19 06:07 UTC, sangeethailango commented on index.html
> +          style="width: 100%"
Don't use inline styling. remove this.

2023-07-19 06:07 UTC, sangeethailango commented on index.html
> +          style="width: 100%"
Looks like you use width 100% for quite lot of images. Just make it as a single class. if you wanted to style alot of things same, Plan accordingly whether you wanted to make it as a single class or seperate id's. Also avoid using inline styling.

2023-07-19 06:07 UTC, sangeethailango commented on index.html
> +    <div id="a">
Why the id name is "a". Make it meaningful.

2023-07-19 06:07 UTC, sangeethailango commented on index.html
> +      </div>
Try to reduce the code size. Instead of writing same footer and header for each and every page, Write header and footer in a seperate file and add wherever you want accordingly.

2023-07-19 06:07 UTC, sangeethailango commented on resources/css/my-index.css
> +.navbar a {
Good that you use different selectors hear.

2023-07-19 06:07 UTC, sangeethailango commented on resources/css/my-index.css
> +  outline: none;
Is this outline: none useful? if it not then remote it. Try to reduce the code size

2023-07-19 06:07 UTC, sangeethailango commented on resources/css/my-index.css
> +
Indent your code properly.

2023-07-19 06:07 UTC, sangeethailango commented on resources/css/my-index.css
> +.title1 {
title1 is not a meaningful name. Change the selector name meaningfully.

2023-07-19 06:07 UTC, sangeethailango commented on resources/css/my-index.css
> +  margin-top: 0%;
looks like margin-top is the only difference between title and title3 class. Remove all code other then margin-top in title3. Pay attention to these kind of mistakes. It will help you to reduce the code size.

2023-07-19 06:07 UTC, sangeethailango commented on resources/css/my-index.css
> +#b {
what is #b? Please make it meaningful.

2023-07-19 06:07 UTC, sangeethailango commented on resources/css/my-index.css
> +  float: right;
Read the below. Search for other resource also to understand if using float is a good practice or not. And send me your view on this.
https://stackoverflow.com/questions/9776840/is-float-for-layout-bad-what-should-be-used-in-its-place

2023-07-19 06:09 UTC, Divyan-H commented on index.html
> +      Vision
It is a button

2023-07-19 08:40 UTC, Divyan-H commented on index.html
> +        <button id="Donation_Guidelines">Donation guidelines</button>
ok done !

2023-07-19 08:54 UTC, Divyan-H commented on index.html
> +      <h1 class="title">News & Events in Auroville</h1>
Ok Done !

2023-07-19 09:05 UTC, Divyan-H commented on index.html
> +          style="width: 100%"
Ok Done !

2023-07-19 09:14 UTC, Divyan-H commented on index.html
> +          style="width: 100%"
ok done  !

2023-07-19 09:18 UTC, Divyan-H commented on index.html
> +    <div id="a">
ok done !

2023-07-19 09:18 UTC, Divyan-H commented on index.html
> +      </div>
I couldn't do it , i tried using js it gives me only html of the external page . I have also tried using object tag , I'm getting scroll bar for it and also behaves llike a artical in a page.

2023-07-19 09:19 UTC, Divyan-H commented on resources/css/my-index.css
> +.navbar a {
ok , thank you

2023-07-19 09:21 UTC, Divyan-H commented on resources/css/my-index.css
> +  outline: none;
ok done !

2023-07-19 09:22 UTC, Divyan-H commented on resources/css/my-index.css
> +
ok done !

2023-07-19 10:43 UTC, Divyan-H commented on resources/css/my-index.css
> +.title1 {
ok done !

2023-07-19 10:45 UTC, Divyan-H commented on resources/css/my-index.css
> +  margin-top: 0%;
ok done !

2023-07-19 10:46 UTC, Divyan-H commented on resources/css/my-index.css
> +#b {
ok done !

2023-07-19 10:48 UTC, Divyan-H commented on resources/css/my-index.css
> +  float: right;
ok , but i can' t change it in nav bar

2023-07-20 04:15 UTC, Divyan-H commented on index.html
> +<div class="navbar">
ok done

2023-07-20 04:15 UTC, Divyan-H commented on index.html
> +
ok done

2023-07-20 04:21 UTC, Divyan-H commented on index.html
> +
ok done

2023-07-20 10:49 UTC, sakthibalan15 approved these changes

2023-07-24 05:28 UTC, Divyan-H commented on index.html
> +<div class="navbar">
ok done

2023-07-25 10:05 UTC, merged